# Generated by Django 5.2.7 on 2025-11-08 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='FitnessTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('pre', 'Pre Test'), ('post', 'Post Test')], max_length=10)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vo2_distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vo2_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flexibility_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('strength_reps', models.IntegerField(blank=True, null=True)),
                ('agility_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speed_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('endurance_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fitness_tests',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_no', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('section_code', models.CharField(max_length=20)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('last_data_update_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='trakfit_app.fitnesstest')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='trakfit_app.student')),
            ],
            options={
                'db_table': 'remarks',
            },
        ),
        migrations.AddField(
            model_name='fitnesstest',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='fitness_tests', to='trakfit_app.student'),
        ),
    ]
