# Generated by Django 5.2.8 on 2025-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnesstest',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='fitnesstest',
            name='endurance_min',
        ),
        migrations.RemoveField(
            model_name='fitnesstest',
            name='vo2_max',
        ),
        migrations.AddField(
            model_name='fitnesstest',
            name='endurance_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnesstest',
            name='endurance_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
