# Generated by Django 5.2.8 on 2025-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0002_remove_fitnesstest_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
