# Generated by Django 5.2.8 on 2025-11-17 23:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0004_alter_student_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstest',
            name='agility_sec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('5')), django.core.validators.MaxValueValidator(Decimal('60'))]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='endurance_minutes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='endurance_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='flexibility_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-20')), django.core.validators.MaxValueValidator(Decimal('50'))]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100')), django.core.validators.MaxValueValidator(Decimal('250'))]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='speed_sec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('4')), django.core.validators.MaxValueValidator(Decimal('20'))]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='strength_reps',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='vo2_distance_m',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('500')), django.core.validators.MaxValueValidator(Decimal('5000'))]),
        ),
        migrations.AlterField(
            model_name='fitnesstest',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30')), django.core.validators.MaxValueValidator(Decimal('200'))]),
        ),
    ]
