# Generated by Django 5.2.8 on 2025-11-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0004_alter_student_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnesstest',
            name='remarksCreated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
