# Generated by Django 5.2.8 on 2025-11-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0005_alter_fitnesstest_agility_sec_and_more'),
        ('trakfit_app', '0005_fitnesstest_remarks_fitnesstest_remarkscreated_and_more'),
    ]

    operations = [
    ]
