# Generated by Django 5.2.8 on 2025-11-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0006_merge_20251118_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='trakfit_app.student')),
            ],
            options={
                'db_table': 'updates',
            },
        ),
    ]
