# Generated by Django 5.2.8 on 2025-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0007_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='updates',
            name='body',
            field=models.TextField(default='exit', help_text='Description of the update action'),
            preserve_default=False,
        ),
    ]
