# Generated by Django 5.2.8 on 2025-11-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0008_alter_updates_options_updates_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
