# Generated by Django 5.2.8 on 2025-11-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakfit_app', '0009_alter_fitnesstest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='exit'),
            preserve_default=False,
        ),
    ]
